app/routes/book.py
"""
A module that Imports book using the Frappe API, adds book to the library database, allows Librarian
to search for books, updates book details, deletes book details, and view all books
"""
from flask import Flask, Blueprint, flash, redirect, url_for, render_template, request
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import InputRequired, Length, NumberRange
from app.models import Book, db
import requests

app = Flask(__name__)

# Create the books blueprint
bp = Blueprint('book', __name__)

class ImportBooksForm(FlaskForm):
    """
    A class that creates a form object to import books
    """
    search = StringField('Search by Title or Author', validators=[InputRequired(), Length(max=255)])
    submit = SubmitField('Search Frappe Library')

class AddBookForm(FlaskForm):
    """
    A class that creates a form object to add books
    """
    author = StringField('Author', validators=[InputRequired(), Length(max=255)])
    title = StringField('Title', validators=[InputRequired(), Length(max=255)])
    publisher = StringField('Publisher', validators=[InputRequired(), Length(max=255)])
    isbn = StringField('ISBN', validators=[InputRequired(), Length(max=20)])
    quantity = IntegerField('Quantity', validators=[InputRequired(), NumberRange(min=1, max=30)])
    submit = SubmitField('Add Book')

class SearchBooksForm(FlaskForm):
    """
    A class that creates a form object to search for books
    """
    search = StringField('Search by Title or Author', validators=[InputRequired(), Length(max=255)])
    submit = SubmitField('Delete')
    submit = SubmitField('Update')

class DeleteBooksForm(FlaskForm):
    """
    A class that creates a form object to delete books
    """
    author = StringField('Author', validators=[InputRequired(), Length(max=255)])
    title = StringField('Title', validators=[InputRequired(), Length(max=255)])
    publisher = StringField('Publisher', validators=[InputRequired(), Length(max=255)])
    isbn = StringField('ISBN', validators=[InputRequired(), Length(max=20)])
    quantity= IntegerField('Quantity', validators=[InputRequired(), NumberRange(min=1, max=30)])
    submit = SubmitField('Delete')

class UpdateBookForm(FlaskForm):
    """
    Class that creates a form object to update book details
    """
    author = StringField('Author', validators=[InputRequired(), Length(max=255)])
    title = StringField('Title', validators=[InputRequired(), Length(max=255)])
    publisher = StringField('Publisher', validators=[InputRequired(), Length(max=255)])
    isbn = StringField('ISBN', validators=[InputRequired(), Length(max=20)])
    submit = SubmitField('Update')

# A route for importing books
@bp.route('/import-books', methods=['GET', 'POST'])
def import_books():
    """
    A route that imports books using the Frappe API
    """
    form = ImportBooksForm()

    if request.method == 'POST' and form.validate_on_submit():
        search_query = form.search.data

        # Define the API URL
        frappe_api_url = "https://frappe.io/api/method/frappe-library"

        # Prepare parameters for the API request
        params = {
            'title': search_query,  # Search by title
            'authors': search_query,  # Search by authors
            'isbn': 1,  
            'publisher': 1,  
        }
        try:
            # Fetch data from the API
            response = requests.get(frappe_api_url, params=params, timeout=10)
            if response.status_code == 200:
                data = response.json()["message"]

                # Filter the API results to include only books with matching titles or authors
                matching_books = [book for book in data if
                                    search_query.lower() in book["title"].lower() or
                                    search_query.lower() in book["authors"].lower()]
                if not matching_books:
                    flash("No matching books found.", "warning")
                return render_template('book/import_books.html', search_results=matching_books, form=form)
            else:
                print("Request failed with timeout:", response.status_code)
        except requests.Timeout:
            print("The request timed out")
    return render_template('book/import_books.html', form=form)

# A route for adding books to library
@bp.route('/add-book', methods=['POST', 'GET'])
def add_book():
    """
    A route that adds books to the database
    """
    # Retrieve book details from the form 
    if request.method == 'POST':
        title = request.form.get('title')
        author = request.form.get('author')
        isbn = request.form.get('isbn')
        publisher = request.form.get('publisher')
    else:
        # Retrieve book details from url parameters
        title = request.args.get('title')
        author = request.args.get('author')
        isbn = request.args.get('isbn')
        publisher = request.args.get('publisher')

    # Create the form and populate it with the book details
    form = AddBookForm(title=title, author=author, isbn=isbn, publisher=publisher)

    if request.method == 'POST' and form.validate_on_submit():
        # Handle the form submission (add the books to the database)
        quantity = form.quantity.data
        # Check if the ISBN exists in the table
        existing_book = Book.query.filter(Book.isbn==isbn).first()
        if existing_book:
            # Increment the db quantity by the librarian's input
            existing_book.Quantity+=quantity
        else:
            new_book = Book(title=title, author=author, isbn=isbn, publisher=publisher, Quantity=quantity)
            db.session.add(new_book)
            
        db.session.commit()
        flash(f'Successfully added {quantity} books to the library!', 'success')
        return redirect(url_for('book.all_books'))

    return render_template('book/add_book.html', form=form)

# Route for deleting books
@bp.route('/delete-book', methods=['GET', 'POST'])
def delete_book():
    """
    A route that deletes books in the database
    """
    # Retrieve book details from query parameters
    title = request.args.get('title')
    author = request.args.get('author')
    isbn = request.args.get('isbn')
    publisher = request.args.get('publisher')

    # Query the database for the book with the specified ISBN
    book_to_delete = Book.query.filter_by(isbn=isbn).first()

    if book_to_delete:
        # Create the form and populate it with the book details
        form = DeleteBooksForm(title=title, author=author, isbn=isbn, publisher=publisher)

        if request.method == 'POST' and form.validate_on_submit():
            quantity_to_delete = form.quantity.data
            existing_quantity = book_to_delete.Quantity

            if quantity_to_delete <= existing_quantity:
                # Update the quantity in the database
                book_to_delete.Quantity -= quantity_to_delete

                db.session.commit()
                flash(f'Successfully deleted {quantity_to_delete} copy(ies) of {book_to_delete.title} from the library!', 'success')
                return redirect(url_for('book.search_books'))
            
            flash('Quantity to delete is greater than existing quantity.', 'warning')
    else:
        flash('Book not found', 'danger')

    return render_template('book/delete_book.html', form=form, book=book_to_delete)

@bp.route('/update-book/<int:book_id>', methods=['GET', 'POST'])
def update_book(book_id):
    """
    A route that updates the properties of a particular book in the database
    """
    book_to_update = Book.query.get(book_id)
    form = UpdateBookForm()

    if book_to_update:
        if request.method == 'GET':
            # Pre-fill the form with book data
            form.title.data = book_to_update.title
            form.author.data = book_to_update.author
            form.isbn.data = book_to_update.isbn
            form.publisher.data = book_to_update.publisher

        if form.validate_on_submit() and request.method == 'POST':
            # Update the book details based on the form data
            book_to_update.title = form.title.data
            book_to_update.author = form.author.data
            book_to_update.isbn = form.isbn.data
            book_to_update.publisher = form.publisher.data
            db.session.commit()
            flash(f"{book_to_update.title} has been successfully updated", "success")
            return redirect(url_for('book.search_books'))
    return render_template('book/update_book.html', form=form, book_to_update=book_to_update, book_id=book_id)

@bp.route('/search-books', methods=['POST', 'GET'])
def search_books():
    """
    A route that allows the librarian to search for any book using title or author
    """
    form = SearchBooksForm()

    book_list = []
    if request.method == 'POST':
        search_query = form.search.data
        # Query the database by author or title
        book_list = Book.query.filter(Book.title.like(f'%{search_query}%') | Book.author.like(f'%{search_query}%')).all()

        if not book_list:
            flash("No matching book copies found in the library")
            return render_template("book/search_books.html", form=form)

    return render_template("book/search_books.html", form=form, book_list=book_list)

@bp.route('/all-books', methods=['GET'])
def all_books():
    """
    A route that displays all books in the library
    """
    # Query the database for all books
    library_books = Book.query.all()
    return render_template('book/all_books.html', library_books=library_books)

app/templates/book/add_book.html
{% extends "layout.html" %} {% block title %} Add Books to Library {% endblock
%} {% block main %}
<br />

<h3 style="text-align: center">Add Books</h3>

<form method="POST" action="/add-book">
  {{ form.hidden_tag() }}

  <!-- Title -->
  <div class="mb-3">
    <strong>{{ form.title.label }}</strong> {{ form.title(class="form-control",
    placeholder="Enter book title") }}
  </div>

  <!-- Author -->
  <div class="mb-3">
    <strong>{{ form.author.label }}</strong> {{ form.author(class="form-control",
    placeholder="Enter author") }}
  </div>

  <!-- ISBN -->
  <div class="mb-3">
    <strong>{{ form.isbn.label }}</strong> {{ form.isbn(class="form-control", placeholder="Enter
    ISBN") }}
  </div>

  <!-- Publisher -->
  <div class="mb-3">
    <strong>{{ form.publisher.label }}</strong> {{ form.publisher(class="form-control",
    placeholder="Enter publisher") }}
  </div>

  <!-- Quantity -->
  <div class="mb-3">
    <strong>{{ form.quantity.label }}</strong> {{ form.quantity(class="form-control",
    placeholder="Enter quantity (1-30)") }}
  </div>

  <!-- Submit Button -->
  <button type="submit" class="btn btn-primary">Add to Library</button>
</form>
{% endblock %}

app/templates/book/all_books.html
{% extends "layout.html" %} {% block title %} All Books {% endblock %} {% block
main %}
<br />

<h3 style="text-align: center">All Books</h3>

<!-- Display All Books Table -->
{% if library_books %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">ISBN</th>
      <th scope="col">Total Copies</th>
    </tr>
  </thead>
  <tbody>
    {% for book in library_books %}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.author }}</td>
      <td>{{ book.isbn }}</td>
      <td>{{ book.Quantity }}</td>
      <td>
        <!-- Add an Update button for each book -->
        <a
          href="{{ url_for('book.update_book', book_id=book.id) }}"
          class="btn btn-primary"
          style="background-color: burlywood; color: black"
          >Update</a
        >
      </td>

      <td>
        <form
          method="POST"
          action="{{ url_for('book.delete_book', title=book.title, author=book.author, isbn=book.isbn, publisher=book.publisher) }}"
        >
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No books available in the library.</p>
{% endif %} {% endblock %}

app/templates/book/delete_book.html
{% extends "layout.html" %} {% block title %} Delete Books From Library {% endblock
%} {% block main %}
<h3>Delete Books from Library</h3><form method="POST" action="/delete-book?title
={{ book.title }}&author={{ book.author }}&isbn={{ book.isbn }}&publisher={{ book.publisher }}">
  {{ form.hidden_tag() }}

  <!-- Title -->
  <div class="mb-3">
    {{ form.title.label }} {{ form.title(class="form-control",
    placeholder="Enter book title") }}
  </div>

  <!-- Author -->
  <div class="mb-3">
    {{ form.author.label }} {{ form.author(class="form-control",
    placeholder="Enter author") }}
  </div>

  <!-- ISBN -->
  <div class="mb-3">
    {{ form.isbn.label }} {{ form.isbn(class="form-control", placeholder="Enter
    ISBN") }}
  </div>

  <!-- Publisher -->
  <div class="mb-3">
    {{ form.publisher.label }} {{ form.publisher(class="form-control",
    placeholder="Enter publisher") }}
  </div>

  <!-- Quantity -->
  <div class="mb-3">
    {{ form.quantity.label }} {{ form.quantity(class="form-control",
    placeholder="Enter quantity to delete (1-50)") }}
  </div>

  <!-- Submit Button -->
  <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

app/templates/book/import_books.html
{% extends "layout.html" %} {% block title %} import Books {% endblock %} {%
block main %}

<br />

<h3 style="text-align: center">Import Books</h3>
<form method="POST" action="/import-books">
  {{ form.hidden_tag() }}

  <!-- Search Bar -->
  <div class="mb-3">
    {{ form.search(class="form-control", placeholder="Search by title or
    author", autocomplete="off") }}
  </div>

  <!-- Search Button -->
  <button type="submit" style="background-color: black; " class="btn btn-primary">Search</button>
</form>

<br />

{% if search_results %}
 <div style="text-align: center;">
    <button type="Text" style="background-color: burlywood; color: black;" class="btn btn-primary">Available Copies</button>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Book Number</th>
      <th>Title</th>
      <th>Author</th>
      <th>ISBN</th>
      <th>Publisher</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for book in search_results %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.authors }}</td>
      <td>{{ book.isbn }}</td>
      <td>{{ book.publisher }}</td>
      <td>
        <form method="POST" action="{{ url_for('book.add_book') }}">
          {{ form.hidden_tag() }}
          <input type="hidden" name="title" value="{{ book.title }}" />
          <input type="hidden" name="author" value="{{ book.authors }}" />
          <input type="hidden" name="isbn" value="{{ book.isbn }}" />
          <input type="hidden" name="publisher" value="{{ book.publisher }}" />
          <button type="submit" class="btn btn-success" style="background-color: black;">Add</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<footer class="mb-5 small text-center text-muted">
      Data provided by <a href="https://frappe.io/">Frappe</a>
    </footer>
{% endif %} {% endblock %}

app/templates/book/search_books.html
{% extends "layout.html" %} {% block title %} Book Database {% endblock %} {%
block main %}

<br />

<h3 style="text-align: center">Search Books</h3>
<!-- Import books button -->
<button
  style="background-color:burlywood; color: black;"
  type="button"
  class="btn btn-success"
  id="import-books"
  onclick="location.href='{{ url_for('book.import_books') }}'"
>
  Import Books
</button>

<!-- View all books button -->
<button
  style="background-color: burlywood; color: black;"
  type="button"
  class="btn btn-success"
  id="all_books"
  onclick="location.href='{{ url_for('book.all_books')}}'"
>
  All Books
</button>

<form method="POST" action="/search-books">
  {{ form.hidden_tag() }}

  <br />

  <!-- Search Input -->
  <div class="mb-3">
    {{ form.search(class="form-control", placeholder="Search by title or
    author", autocomplete="off") }}
  </div>

  <!-- Submit Button -->
  <button type="submit" class="btn btn-primary">Search</button>
</form>

<!-- Display Book Table -->
{% if book_list %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">ISBN</th>
      <th scope="col">Total Copies</th>
    </tr>
  </thead>
  <tbody>
    {% for book in book_list %}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.author }}</td>
      <td>{{ book.isbn }}</td>
      <td>{{ book.Quantity }}</td>
      <td>
        <!-- Add an Update button for each book -->
        <a
          style="background-color: black;"
          href="{{ url_for('book.update_book',  book_id=book.id) }}"
          class="btn btn-primary"
          >Update</a
        >
      </td>
      <td>
        <form
          method="POST"
          action="{{ url_for('book.delete_book', title=book.title, author=book.author, isbn=book.isbn, publisher=book.publisher) }}"
        >
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% endblock %}

app/templates/book/update_book.html
{% extends "layout.html" %} 
{% block title %} Update Books in Library {% endblock %} 
{% block main %}
<h3>Update Books in Library</h3>
<form method="POST" action="/update-book/{{book_to_update.id}}">
  {{ form.hidden_tag() }}

  <!-- Title -->
  <div class="mb-3">
    {{ form.title.label }} {{ form.title(class="form-control", placeholder="Enter book title") }}
  </div>

  <!-- Author -->
  <div class="mb-3">
    {{ form.author.label }} {{ form.author(class="form-control", placeholder="Enter author") }}
  </div>

  <!-- ISBN -->
  <div class="mb-3">
    {{ form.isbn.label }} {{ form.isbn(class="form-control", placeholder="Enter ISBN") }}
  </div>

  <!-- Publisher -->
  <div class="mb-3">
    {{ form.publisher.label }} {{ form.publisher(class="form-control", placeholder="Enter publisher") }}
  </div>

  <!-- Submit Button -->
  <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}